sonar.projectKey=disha-sharma11_aboriginal-art-gallery
sonar.projectName=Aboriginal Art Gallery
sonar.projectVersion=1.0
sonar.organization=disha-sharma11
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/AboriginalArtGallery.Api,frontend/src
sonar.tests=backend/AboriginalArtGallery.Api.Tests,frontend/src
sonar.test.inclusions=backend/AboriginalArtGallery.Api.Tests/**/*.cs,frontend/src/**/*.test.js
sonar.exclusions=**/bin/**,**/obj/**,**/node_modules/**,frontend/build/**,backend/AboriginalArtGallery.Api/Migrations/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.cs.vstest.reportsPaths=artifacts/test-results/backend/*.trx
sonar.sourceEncoding=UTF-8
